version: '2'
services:
  moodle:
    image: docker.io/bitnami/moodle:4
    restart: always
    ports:
      - '80:8080'
    environment:
      - MOODLE_DATABASE_HOST=moodlereds1.c2nu2sypx880.us-east-1.rds.amazonaws.com
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=moodleuser
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_DATABASE_PASSWORD=moodlepassword
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
    volumes:
      - '/mnt/moodle/moodle_data:/bitnami/moodle'
      - '/mnt/moodle/moodledata_data:/bitnami/moodledata'
